// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdzLnI7Evb_FogAq8w7D8Pxao62UPxAYc',
    appId: '1:48604813225:web:87c5b05e71d703d04496b8',
    messagingSenderId: '48604813225',
    projectId: 'chat-app-a776b',
    authDomain: 'chat-app-a776b.firebaseapp.com',
    storageBucket: 'chat-app-a776b.appspot.com',
    measurementId: 'G-GZ3DYWRGY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUVTvF0UIorbpCU7jKGaEziVAlmHQHRu8',
    appId: '1:48604813225:android:896be261cfa637714496b8',
    messagingSenderId: '48604813225',
    projectId: 'chat-app-a776b',
    storageBucket: 'chat-app-a776b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8MZJYltdrbf8APs_d24B0sTJ4bGiLXq0',
    appId: '1:48604813225:ios:69a936b6257417de4496b8',
    messagingSenderId: '48604813225',
    projectId: 'chat-app-a776b',
    storageBucket: 'chat-app-a776b.appspot.com',
    iosClientId: '48604813225-k2p3l024d8l9cpa1ioiuqhtbp375ad22.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8MZJYltdrbf8APs_d24B0sTJ4bGiLXq0',
    appId: '1:48604813225:ios:c5f237fa127f7cd94496b8',
    messagingSenderId: '48604813225',
    projectId: 'chat-app-a776b',
    storageBucket: 'chat-app-a776b.appspot.com',
    iosClientId: '48604813225-arp91ktkb8n47a1g3t4ol5o7baj4i810.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
